### ISSUE TITLE
Use codemode=objectgenerator for dc.SecurityMediator.SecurityMediator:AccessCheck

### ISSUE THREAD

**Issue by isc-tleavitt** [yurimarx/iris-api-security-mediator#2]
You could reduce the runtime overhead of access checking by generating the AccessCheck method. (Shouldn't need to do runtime lookups against the class dictionary - those are often slow.)

**Comment by isc-tleavitt** [comment]
Same with GetClassMethodName

**Comment by yurimarx** [comment]
When I do this, I get <INVALID CLASS>AccessCheck+1^dc.SecurityMediator.SecurityMediator.G1 *super-class '%CSP.REST' is not in sub-class '%Studio.Project' hierarchy

So, it is not possible set codemode=objectgenerator, because an InterSystems IRIS class, the %CSP.REST.

**Comment by isc-tleavitt** [comment]
That's a very strange error... how is %Studio.Project involved?

**Comment by yurimarx** [comment]
I did not used Studio, I used vscode. But %CSP.REST extends the class %Studio.Project, an InterSystems class. So, is impossível to do codemode=objectgenerator. Can I close this issue?

**Comment by yurimarx** [comment]
Not possible to apply
